# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  streamnestapi:
    image: streamnestapi
    build:
      context: .
      dockerfile: StreamNest.API/Dockerfile
    ports:
      - 5213:5213
